name: update-flake-lock
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: "0 0 * * 0" # runs weekly on Sunday at 00:00

jobs:
  lockfile:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install Determinate Nix
        uses: DeterminateSystems/determinate-nix-action@v3

      # - name: Update flake.lock
      #   uses: DeterminateSystems/update-flake-lock@main
      #   with:
      #     nix-options: --debug --log-format raw

      - name: nix flake update
        run: |
          git config --global user.email    "github-actions[bot]@users.noreply.github.com"
          git config --global user.name     "github-actions[bot]"
          nix flake update --commit-lock-file
          git push
